name: time-tz CI build

on:
  - push
  - pull_request

jobs:
  check-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive # garbage peace of shit mother fucking github downloading broken repositories!!!!!
          # GitLab is far better because it is not downloading broken repositories.
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Run audit
        run: cargo audit
  check-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive # garbage peace of shit mother fucking github downloading broken repositories!!!!!
          # GitLab is far better because it is not downloading broken repositories.
      - name: Install clippy
        run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive # garbage peace of shit mother fucking github downloading broken repositories!!!!!
          # GitLab is far better because it is not downloading broken repositories.
      - name: Build and test
        run: cargo test --all-features
  build-test-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive # garbage peace of shit mother fucking github downloading broken repositories!!!!!
          # GitLab is far better because it is not downloading broken repositories.
      - name: Install rustwasm
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build and test for WASM
        run: wasm-pack test --all-features
